config/routes.rb
resources :projects do
  resource :create_due_date
  resource :update_due_date
end

app/models/create_due_date.rb
class CreateDueDate < ActiveRecord::Base
  validates :project_id, presence: true, uniqueness: true
  validates :days, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/update_due_date.rb
class UpdateDueDate < ActiveRecord::Base
  validates :project_id, presence: true, uniqueness: true
  validates :days, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/create_due_dates_controller.rb
class CreateDueDatesController < ApplicationController
  before_action :find_project_by_project_id
  before_action :authorize

  def show
    @create_due_date = CreateDueDate.where(project_id: @project.id).first
    @settings = Setting.plugin_redmine_auto_due_date
  end

  def new
    @create_due_date = CreateDueDate.new(project_id: @project.id)
  end

  def create
    params[:create_due_date][:project_id] = @project.id

    @create_due_date = CreateDueDate.new(create_due_date_params)

    if @create_due_date.save
      flash[:notice] = l(:create_due_date_created, scope: :auto_due_date)

      redirect_to project_create_due_date_path(@project)
    else
      render('new')
    end
  end

  def edit
    @create_due_date = CreateDueDate.where(project_id: @project.id).first
  end

  def update
    @create_due_date = CreateDueDate.where(project_id: @project.id).first

    if @create_due_date.update_attributes(create_due_date_params)
      flash[:notice] = l(:create_due_date_updated, scope: :auto_due_date)

      redirect_to project_create_due_date_path(@project)
    else
      render('edit')
    end
  end

  def destroy
    @create_due_date = CreateDueDate.where(project_id: @project.id).first

    @create_due_date.destroy

    flash[:notice] = l(:create_due_date_deleted, scope: :auto_due_date)

    redirect_to project_create_due_date_path
  end

  private

  def create_due_date_params
    params.require(:create_due_date).permit(:days, :project_id)
  end
end

app/controllers/update_due_dates_controller.rb
class UpdateDueDatesController < ApplicationController
  before_action :find_project_by_project_id
  before_action :authorize

  def show
    @update_due_date = UpdateDueDate.where(project_id: @project.id).first
    @settings = Setting.plugin_redmine_auto_due_date
  end

  def new
    @update_due_date = UpdateDueDate.new(project_id: @project.id)
  end

  def create
    params[:update_due_date][:project_id] = @project.id

    @update_due_date = UpdateDueDate.new(update_due_date_params)

    if @update_due_date.save
      flash[:notice] = l(:update_due_date_updated, scope: :auto_due_date)

      redirect_to project_update_due_date_path(@project)
    else
      render('new')
    end
  end

  def edit
    @update_due_date = UpdateDueDate.where(project_id: @project.id).first
  end

  def update
    @update_due_date = UpdateDueDate.where(project_id: @project.id).first

    if @update_due_date.update_attributes(update_due_date_params)
      flash[:notice] = l(:update_due_date_updated, scope: :auto_due_date)

      redirect_to project_update_due_date_path(@project)
    else
      render('edit')
    end
  end

  def destroy
    @update_due_date = UpdateDueDate.where(project_id: @project.id).first

    @update_due_date.destroy

    flash[:notice] = l(:update_due_date_deleted, scope: :auto_due_date)

    redirect_to project_update_due_date_path
  end

  private

  def update_due_date_params
    params.require(:update_due_date).permit(:days, :project_id)
  end
end

app/views/create_due_dates/_create_due_date.html.erb
<%= l(:current_value, value: create_due_date.days, scope: :auto_due_date) %>

<span class="float-right">
  <%= link_to(l(:edit_link, scope: :auto_due_date), edit_project_create_due_date_path(project)) %>

  <span>|</span>

  <%= link_to(l(:delete_link, scope: :auto_due_date), project_create_due_date_path(project), method: :delete) %>
</span>

app/views/create_due_dates/_form.html.erb
<%=
  form_for([project, create_due_date], url: project_create_due_date_path(project)) do |f|
%>
  <% if create_due_date.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(create_due_date.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% create_due_date.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="box tabular">
    <p>
      <%= f.label :days, class: create_due_date.errors.any? ? 'errors' : ''  do %>
        <%= l(:days, scope: :auto_due_date) %>
        <span class="required">*</span>
      <% end %>
      <%= f.text_field :days, type: 'number', required: true, min: 0 %>
    </p>
  </div>

  <p>
    <%= f.submit l(create_due_date.new_record? ? :create_btn : :update_btn, scope: :auto_due_date) %>
  </p>
<%
  end
%>

app/views/create_due_dates/edit.html.erb
<% html_title l(:create_due_date_menu_title, scope: :auto_due_date) %>

<div>
  <%= link_to(l(:home_link, scope: :auto_due_date), project_create_due_date_path(@project)) %>
</div>

<div>
  <%= render partial: 'form', locals: { project: @project, create_due_date: @create_due_date } %>
</div>

app/views/create_due_dates/new.html.erb
<% html_title l(:create_due_date_menu_title, scope: :auto_due_date) %>

<div>
  <%= link_to(l(:home_link, scope: :auto_due_date), project_create_due_date_path(@project)) %>
</div>

<div>
  <%= render partial: 'form', locals: { project: @project, create_due_date: @create_due_date } %>
</div>

app/views/create_due_dates/show.html.erb
<% html_title l(:create_due_date_menu_title, scope: :auto_due_date) %>

<div>
  <div class="box">
    <%= l(:default_value, value: @settings['create_due_date'].to_i, scope: :auto_due_date) %>

    <span class="float-right">
      <%= link_to_if(User.current.admin?, l(:settings_link, scope: :auto_due_date),
                     plugin_settings_path('redmine_auto_due_date')) %>

      <% if(@create_due_date.nil?) %>
        <span>|</span>

        <%= link_to(l(:new_link, scope: :auto_due_date), new_project_create_due_date_path(@project)) %>
      <% end %>
    </span>
  </div>

  <% unless(@create_due_date.nil?) %>
    <div class="box">
      <%= render partial: 'create_due_date', object: @create_due_date, locals: { project: @project } %>
    </div>
  <% end %>
</div>

app/views/settings/_auto_due_date.html.erb
<fieldset>
  <legend><%= l(:create_due_date_fieldset, scope: :auto_due_date) %></legend>
  <p>
    <%= label 'settings[create_due_date]', l(:days, scope: :auto_due_date) %>
    <%= text_field_tag 'settings[create_due_date]', @settings['create_due_date'], type: 'number', required: true,
                       min: 0 %>
    <%= content_tag :em, l(:create_due_date_info, scope: :auto_due_date), class: 'info' %>
  </p>
</fieldset>

<fieldset>
  <legend><%= l(:update_due_date_fieldset, scope: :auto_due_date) %></legend>
  <p>
    <%= label 'settings[update_due_date]', l(:days, scope: :auto_due_date) %>
    <%= text_field_tag 'settings[update_due_date]', @settings['update_due_date'], type: 'number', required: true,
                       min: 0 %>
    <%= content_tag :em, l(:update_due_date_info, scope: :auto_due_date), class: 'info' %>
  </p>
</fieldset>

app/views/update_due_dates/_form.html.erb
<%=
  form_for([project, update_due_date], url: project_update_due_date_path(project)) do |f|
%>
  <% if update_due_date.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(update_due_date.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% update_due_date.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="box tabular">
    <p>
      <%= f.label :days, class: update_due_date.errors.any? ? 'errors' : ''  do %>
        <%= l(:days, scope: :auto_due_date) %>
        <span class="required">*</span>
      <% end %>
      <%= f.text_field :days, type: 'number', required: true, min: 0 %>
    </p>
  </div>

  <p>
    <%= f.submit l(update_due_date.new_record? ? :create_btn : :update_btn, scope: :auto_due_date) %>
  </p>
<%
  end
%>

app/views/update_due_dates/_update_due_date.html.erb
<%= l(:current_value, value: update_due_date.days, scope: :auto_due_date) %>

<span class="float-right">
  <%= link_to(l(:edit_link, scope: :auto_due_date), edit_project_update_due_date_path(project)) %>

  <span>|</span>

  <%= link_to(l(:delete_link, scope: :auto_due_date), project_update_due_date_path(project), method: :delete) %>
</span>

app/views/update_due_dates/edit.html.erb
<% html_title l(:update_due_date_menu_title, scope: :auto_due_date) %>

<div>
  <%= link_to(l(:home_link, scope: :auto_due_date), project_update_due_date_path(@project)) %>
</div>

<div>
  <%= render partial: 'form', locals: { project: @project, update_due_date: @update_due_date } %>
</div>

app/views/update_due_dates/new.html.erb
<% html_title l(:update_due_date_menu_title, scope: :auto_due_date) %>

<div>
  <%= link_to(l(:home_link, scope: :auto_due_date), project_update_due_date_path(@project)) %>
</div>

<div>
  <%= render partial: 'form', locals: { project: @project, update_due_date: @update_due_date } %>
</div>

app/views/update_due_dates/show.html.erb
<% html_title l(:update_due_date_menu_title, scope: :auto_due_date) %>

<div>
  <div class="box">
    <%= l(:default_value, value: @settings['update_due_date'].to_i, scope: :auto_due_date) %>

    <span class="float-right">
      <%= link_to_if(User.current.admin?, l(:settings_link, scope: :auto_due_date),
                     plugin_settings_path('redmine_auto_due_date')) %>

      <% if(@update_due_date.nil?) %>
        <span>|</span>
        
        <%= link_to(l(:new_link, scope: :auto_due_date), new_project_update_due_date_path(@project)) %>
      <% end %>
    </span>
  </div>

  <% unless(@update_due_date.nil?) %>
    <div class="box">
      <%= render partial: 'update_due_date', object: @update_due_date, locals: { project: @project } %>
    </div>
  <% end %>
</div>